apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: test
spec:
  nodeName: master  # 将 <master-node-name> 替换为 Master 节点的名称
  containers:
    - name: network-multitool
      image: praqma/network-multitool:latest
      
