apiVersion: v1
kind: Service
metadata:
  name: pod2-service
  namespace: test
spec:
  selector:
    app: pod2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
  clusterIP: 10.1.118.185
