apiVersion: v1
kind: Service
metadata:
  name: openeuler-service
  labels:
    app: openeuler-service
    service: openeuler-service
spec:
  selector:
    app: openeuler
  type: NodePort
  ports:
  - name: http
#    nodePort: 30080
    port: 9080
    targetPort: 80
  - name: https
#    nodePort: 30443
    port: 9443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeuler-v1
  labels:
    app: openeuler
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openeuler
      version: v1
  template:
    metadata:
      labels:
        app: openeuler
        version: v1
    spec:
      containers:
      - name: openeuler
        image: openeuler-20.03-lts-sp1:latest
        command: ["/sbin/init"]
        imagePullPolicy: IfNotPresent #Always
        ports:
        - protocol: TCP
          containerPort: 80
          containerPort: 433
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeuler-v2
  labels:
    app: openeuler
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openeuler
      version: v2
  template:
    metadata:
      labels:
        app: openeuler
        version: v2
    spec:
      containers:
      - name: openeuler
        image: openeuler-20.03-lts-sp1:latest
        command: ["sbin/init"]
        imagePullPolicy: IfNotPresent #Always
        ports:
        - protocol: TCP
          containerPort: 80
          containerPort: 433
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi
